image:
  name: node:13

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm install -g gatsby-cli
  script:
    - npm install
    - npm run build
  only:
    - master
  cache:
    untracked: true
    policy: push
    key: public
    paths:
      - ./public

deploy:
  stage: deploy
  before_script:
    - apt-get install --no-cache curl python
    - apt-get upgrade
    - curl https://bootstrap.pypa.io/2.6/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:$PATH
    - aws configure set default.region us-east-1
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  script:
    - npm run deploy
  only:
    - master
  cache:
    key: public
    paths:
      - ./public
    policy: pull
